### PR TITLE
include json_schemer in runtime deps

### PR DESCRIPTION
**Pull request by djordjelacmanovic**
Currently if we want to use the custom RSpec matchers to validate JSON schema we need to manually install `json_schemer` in our app. With this change that is no longer necessary as this lib will list it as a runtime dependency.

### CODE REVIEW

**Review by melcha — APPROVED** [review]
Will we also include custom rspec matchers for json schemer in this gem?
@d4be4st @nikajukic

**Review by nikajukic — APPROVED** [review]
👌

**Comment by nikajukic** [comment]
@melcha they're already included: https://github.com/infinum/infinum-json-api-setup/blob/master/lib/infinum_json_api_setup/rspec/matchers/schema_matchers.rb

**Comment by melcha** [comment]
@djordjelacmanovic you can merge it then 👍 thanks!

**Pull request merged**
